title: About Artificial Intelligence
description: Different Kinds of Artifical Intelligence
url: "https://sehwanhong.github.io"
baseurl: "/Artificial-Intelligence"

collections:
  FAS:
    output: true
  ToNN:
    output: true